language: swift
osx_image: xcode11.3
before_install:
  - brew install python
  - pip install requests
script:
  - xcodebuild -scheme standard-swift -sdk iphonesimulator -derivedDataPath Build/ -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1' -enableCodeCoverage YES clean build test
  - cd Build/Build/ProfileData
  - cd $(ls -d */|head -n 1)
  - directory=${PWD##*/} 
  - pathCoverage=Build/Build/ProfileData/${directory}/Coverage.profdata
  - cd ../../../../
  - xcrun llvm-cov export -format="lcov" -instr-profile $pathCoverage Build/Build/Products/Debug-iphonesimulator/standard-swift.app/standard-swift > info.lcov
  - bash <(curl https://codecov.io/bash)
  - python request.py
